name: Kiota Library

on:
    push:
      branches: 
        [ main ]
      paths:
      - 'src/Codebreaker.GameAPIs.KiotaClient/**'
      - '.github/workflows/shared-create-nuget.yml'
      - '.github/workflows/shared-githubpackages.yml'
      - '.github/workflows/kiota-lib.yml'
  
    workflow_dispatch:

jobs:
    build-and-test:
        uses: ./.github/workflows/shared-create-nuget.yml
        with:
          version-suffix: beta.
          build-number: ${{ github.run_number }}
          build-offset: 42
          solutionfile-path: 'src/ClientLib.sln'
          projectfile-path: 'src/Codebreaker.GameAPIs.KiotaClient/Codebreaker.GameAPIs.KiotaClient.csproj'
          artifact-name: 'KiotaLib'

    publish-to-github-packages:
        uses: ./.github/workflows/shared-githubpackages.yml
        needs: build-and-test
        with:
            artifact-name: 'KiotaLib'
            username: 'christiannagel'
            namespace: 'codebreakerapp'
        secrets: inherit